import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqSections = [
  {
    title: "Series & Videos",
    questions: [
      {
        question: "What is a Series?",
        answer: "A Series is an automated content pipeline for a specific niche or topic. Once you create a series, our AI will continuously generate unique videos based on your chosen theme and automatically post them to your connected social media accounts."
      },
      {
        question: "Can I create videos in any niche?",
        answer: "Yes! You can choose from our preset list of popular niches or create a custom prompt for any topic you want. Our AI is trained to create engaging content across virtually any subject matter."
      },
      {
        question: "What social media platforms do you support posting to?",
        answer: "We currently support auto-posting to TikTok, YouTube Shorts, and Instagram Reels. Simply connect your accounts and we'll handle the rest."
      },
      {
        question: "Are the videos unique?",
        answer: "Absolutely! Every video generated by our AI is completely unique. We use advanced algorithms to ensure no two videos are the same, even within the same series."
      },
      {
        question: "Can I edit the videos?",
        answer: "Yes, you have full control to preview and customize any video before it's posted. You can edit the script, title, images, voiceover, and background music."
      },
      {
        question: "How do custom prompts work?",
        answer: "Custom prompts allow you to give specific instructions to our AI about the type of content you want. You can specify tone, style, topics to cover, and any other details to make your videos exactly what you're looking for."
      },
    ]
  },
  {
    title: "Billing",
    questions: [
      {
        question: "Is there a free trial?",
        answer: "Yes! You can create one free video to test out the platform. No credit card required."
      },
      {
        question: "Can I cancel at anytime?",
        answer: "Absolutely. You can cancel your subscription at any time from your account settings. Your access will continue until the end of your billing period."
      },
      {
        question: "How does the membership work?",
        answer: "Choose a plan based on how frequently you want to post. Each plan includes automatic video generation, posting, and all premium features. Your subscription renews monthly or yearly depending on your choice."
      },
      {
        question: "Can I get a refund?",
        answer: "We offer a satisfaction guarantee. If you're not happy with the service within the first 7 days, contact our support team for a full refund."
      },
    ]
  }
];

export function FAQ() {
  return (
    <section className="py-24 bg-background">
      <div className="container mx-auto px-4 max-w-4xl">
        {/* Section header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground">
            Have a question? We have answers.
          </p>
        </div>

        {/* FAQ sections */}
        <div className="space-y-12">
          {faqSections.map((section) => (
            <div key={section.title}>
              <h3 className="text-2xl font-bold mb-6 gradient-text">
                # {section.title}
              </h3>
              <Accordion type="single" collapsible className="space-y-4">
                {section.questions.map((item, index) => (
                  <AccordionItem 
                    key={index} 
                    value={`${section.title}-${index}`}
                    className="border border-border rounded-xl px-6 data-[state=open]:bg-secondary/50"
                  >
                    <AccordionTrigger className="text-left font-semibold hover:no-underline py-4">
                      {item.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground pb-4">
                      {item.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
